services:
  audio-processor:
    build: .
    container_name: audio-processor-worker
    restart: unless-stopped
    env_file:
      - .env
    environment:
      # c7-large 최적화 환경 변수
      - WORKER_PROCESSES=2
      - CONCURRENCY=4
      - OMP_NUM_THREADS=2
      - NUMBA_CACHE_DIR=/tmp/numba_cache
      - LIBROSA_CACHE_DIR=/tmp/librosa_cache
    # c7-large 리소스 최적화 (2 vCPU, 4GB RAM)
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 3.8G  # 시스템용 여유 공간 확보
        reservations:
          cpus: '1.5'
          memory: 2G
    # 성능 최적화 설정
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
      memlock:
        soft: -1
        hard: -1
    # tmpfs 마운트로 임시 파일 성능 최적화
    tmpfs:
      - /tmp:size=1G,exec,noatime
    # 로그는 docker logs로 확인
    healthcheck:
      test: ["CMD", "python", "-c", "from app.celery_app import celery_app; print('OK')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s