services:
  audio-processor:
    build: .
    container_name: audio-processor-worker
    restart: unless-stopped
    env_file:
      - .env
    # 로그는 docker logs로 확인
    healthcheck:
      test: ["CMD", "python", "-c", "from app.celery_app import celery_app; print('OK')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s